version: "3.9"

volumes:
  wedding-uploads:

services:
  wedding:
    build: .
    container_name: wedding-planner
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wedding-uploads:/app/uploads
